inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
   - app/channels/**/*
   - node_modules/**/*
   - bin/*
   - test/**/*
   - spec/**/*
   - lib/*
   - db/**/*
   - lib/tasks/*
   - public/*
   - tmp/*
   - vendor/**/*
   - config/spring.rb
   - config/application.rb
   - config/environments/*
   - config/puma.rb


Style/Documentation:
 Description: 'Document classes and non-namespace modules.'
 Enabled: false

Metrics/LineLength:
 Description: 'This cop checks the length of lines in the source code.'
 Max: 120

Style/ClassAndModuleChildren:
 Descriotion: 'This cop checks the style of children definitions at classes and modules.'
 EnforcedStyle: compact

Style/FrozenStringLiteralComment:
 Enabled: false